### PR TITLE
Upgrade to time 0.2

### PR DESCRIPTION
**Pull request by c410-f3r**
Is it possible to also merge #72? This project is bringing duplicated dependencies to downstream crates

### CODE REVIEW

**Comment by c410-f3r** [comment]
pint @seanmonstar

**Comment by novacrazy** [comment]
Would be great to get this merged. Duplicate dependencies are a pain.

**Comment by theduke** [comment]
@seanmonstar friendly ping again.

The duplicated dependency is annoying me as well.

I ran the tests on current nightly and they work fine, so the CI failure is either spurious or not relevant anymore.

**Comment by seanmonstar** [comment]
Oh right, we did this in hyper earlier... Instead of upgrading `time`, it'd probably be better to take a smaller dependency. In hyper, we depend on `httpdate`, since we don't actually need all the stuff in time.

**Comment by c410-f3r** [comment]
Closing this PR due to stagnation and lack of feedback.

**Pull request closed without merging**
