### PR TITLE
Add an iter method on SetCookie

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by seanmonstar** [comment]
The `SetCookie` should probably return an iterator over some typed `Cookie` instead. Returning a reference `&HeaderValue` here would make it impossible to change the type and still return a reference (unless that new type still contained a `HeaderValue` internally...).

**Comment by Eijebong** [comment]
I'm not sure what to return here. You said that you didn't want to depend on cookie-rs for now.

**Comment by seanmonstar** [comment]
That's true. I don't think this typed header is that useful at the moment. I'd rather it only gain functionality like I mentioned. So far, this type doesn't really provide anything over `headers.get_all(SET_COOKIE)`, besides a `Vec` allocation.

**Comment by Eijebong** [comment]
Right. I did it without this

**Pull request closed without merging**
