### PR TITLE
Don't return a valid AccessControlAllowHeaders if there's an invalid name in it

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by seanmonstar** [comment]
Is it necessary to detect if there's a bad header name immediately, instead of simply omitting it in the iterator, like before?

**Comment by Eijebong** [comment]
Apparently it is because this breaks a few servo tests that were passing before. Also this is wrong as it breaks tests. I'm trying to fix it

**Comment by seanmonstar** [comment]
Would you mind linking to the tests that are failing because of this?

**Comment by Eijebong** [comment]
https://github.com/servo/servo/pull/21644#issuecomment-428756328

**Comment by seanmonstar** [comment]
Hm, interesting test. I tried looking through https://fetch.spec.whatwg.org/#http-cors-protocol, and I don't see anything specifically mentioning that behavior...

In this header's case, my concern is with allocating an extra `Vec` when there should probably be a way to keep it in a flattened CSV buffer...

**Comment by Eijebong** [comment]
Well if you can think of anything I'll take it because right now the borrow checker is hating on me...

**Comment by seanmonstar** [comment]
I believe this change would make the servo test happy:

```rust
self
    .0
    .iter()
    .map(|s| {
        s.parse().ok()
    })
    .take_while(|val| val.is_some())
    .filter_map(|val| val)
```

**Comment by Eijebong** [comment]
There, changed it to your version. Not sure if it's the right thing to do but it'll make servo happier

**Pull request merged**
