### PR TITLE
Core Header trait changes

### LINKED ISSUE #24: Core Header trait
This issue is to discuss the core `Header` trait design.

It's currently this:

```rust
pub trait Header {
    /// The name of this header.
    const NAME: &'static HeaderName;

    /// Decode this type from a `HeaderValue`.
    fn decode(values: &mut Values) -> Option<Self>
    where
        Self: Sized;

    /// Encode this type to a `HeaderMap`.
    ///
    /// This function should be infallible. Any errors converting to a
    /// `HeaderValue` should have been caught when parsing or constructing
    /// this value.
    fn encode(&self, values: &mut ToValues);
}

/// An iterator of `HeaderValue`s supplied to `Header::decode`.
#[derive(Debug)]
pub struct Values<'a> {
    // ..
}

/// A builder to append `HeaderValue`s to during `Header::encode`.
#[derive(Debug)]
pub struct ToValues<'a> {
    // ..
}

impl<'a> ToValues<'a> {
    /// Append the `HeaderValue` to the existing list of headers.
    ///
    /// While this can be called multiple times, *most* headers should only
    /// call this once. The exceptions are outliers like `Set-Cookie`.
    pub fn append(&mut self, value: HeaderValue) {
        // ..
     }

    /// Append the `impl Display` to the list of headers.
    ///
    /// # Panics
    ///
    /// Encoding `HeaderValue`s is expected to be infallible. However, not
    /// all UTF-8 sequences are valid for a `HeaderValue`. The type passed
    /// here must ensure that its resulting string is a valid `HeaderValue`.
    pub fn append_fmt<T: fmt::Display>(&mut self, fmt: T) {
        // ..
     }
}
```

Is this a good design?

### PR DESCRIPTION
**Pull request by seanmonstar**
- `Header::decode` is now generic over an `Iterator`, and so `Values` is removed.
- `Header::encode` is now generic over an `Extend`, and so `ToValues` is made private. This also means there's no more public `append_fmt`.
- Adds `headers::Error`, which is returned by `Header::decode`. `HeaderMap::typed_try_get` returns `Result<Option<T>, Error>`, so that users may know if there was an existing header that failed to decode.

Closes #24

### CODE REVIEW

**Comment by nox** [comment]
The regression is fixed by https://github.com/hyperium/headers/commit/7bd0e0e69a81e2fe03cb5a43615de0f8deb1faa4.

Is there any way to publish either a new `headers-ext` version with that fix, or publish `headers` as `0.1.0` ASAP?

**Comment by seanmonstar** [comment]
Sure. I'd hoped to get mime 0.4 released, since headers depends on it, but whatever, we can just get to a new release quickly-ish.

**Comment by nox** [comment]
I made a mistake and applied 7bd0e0e69a81e2fe03cb5a43615de0f8deb1faa4 on top of 8be213553923431adc4d5e08973b6f16b064d587, which didn't include the commit 37aedacf448e67c1af29d2c10ab599c9aaf8be6d anyway. The regressions are still present in Servo with `headers` 0.2.0.

**Comment by nox** [comment]
For example, all the tests without `""` in this snippet.

https://github.com/servo/servo/blob/0e99ddd6fdf1d66c8912eb0e9ef69f09f234ab52/tests/wpt/web-platform-tests/cors/origin.htm#L106:L123

**Comment by nox** [comment]
Making `OriginOrNull::try_from_values` and `ContentType::decode` use `IterExt::just_one` fixes all the test failures in Servo.

**Pull request merged**
