### PR TITLE
implement as_str(), Display for Referer

### PR DESCRIPTION
**Pull request by goto-bus-stop**
So you can get the value out 😇 I just copied the implementation from the `UserAgent` type.

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
ok, tests were failing for good reason, i forgot to run them locally first…

**Comment by seanmonstar** [comment]
Thanks for the PR! 😀 

I haven't really thought about this, but curious to hear what you think: is it right to model the Referer as always a UTF-8 string? I guess it's usually going to be a URI, right? And so far in `http`, we've assumed that needs to be UTF-8...

**Comment by goto-bus-stop** [comment]
i think it's OK to model it as always a URI … technically you could make a request that has some arbitrary data in there, but i don't think anyone intentionally wants to _receive_ non-URIs in the referer field. browsers would only send a URI.

**Comment by seanmonstar** [comment]
Actually, that reminds me. If we expose an `as_str()`, then we can't ever change this header to actually hold an `http::Uri`, for example, since that splits the string into 3 pieces. What if we just merge an `impl Display` for now?

**Comment by jplatte** [comment]
With #122 merged, I think this should be closed.

**Comment by goto-bus-stop** [comment]
great! 😁

**Pull request closed without merging**
