### PR TITLE
Implement Display for Referer

### PR DESCRIPTION
**Pull request by AsamK**
Based on #95, but just adds impl Display

### CODE REVIEW

**Comment by LeoniePhiline** [comment]
This would be very great to have reviewed and merged! :)

**Comment by m1guelpf** [comment]
Any updates on this?

**Comment by LeoniePhiline** [comment]
ping :) @seanmonstar

**Comment by seanmonstar** [comment]
There's no need to ping the issue/me multiple times.

**Comment by LeoniePhiline** [comment]
It unfortunately appeared quite as if all activity without a personal mention had gone unnoticed.

**Comment by pongsakornsemsuwan** [comment]
Hi, 
What's everyone workaround while waiting for this PR?
I think we can use custom header but I don't want client to manually put it.

**Comment by LeoniePhiline** [comment]
@pongsakornsemsuwan `HeaderMap::get()`:

```rust
async fn newsletter_subscribe<P: NewsletterSubscriptionProvider, M: Mailer + 'static>(
    // Cannot currently use Typed headers, as Referer does not (yet) implement Display: https://github.com/hyperium/headers/pull/122
    // TypedHeader(user_agent): TypedHeader<UserAgent>,
    // TypedHeader(referrer): TypedHeader<axum::headers::Referer>,
    headers: HeaderMap,
    InsecureClientIp(user_ip): InsecureClientIp,
    State(state): State<Arc<NewsletterState<P, M>>>,
    ValidatedJson(payload): ValidatedJson<SubscribeRequest>,
) -> Result<impl IntoResponse> {
    let referrer = match headers.get(header::REFERER) {
        Some(header_value) => header_value
            .to_str()
            .map_err(ClientError::HeaderToStrError)?,
        None => "https://www.example.com",
    };
    let user_agent = match headers.get(header::USER_AGENT) {
        Some(header_value) => header_value
            .to_str()
            .map_err(ClientError::HeaderToStrError)?,
        None => "",
    };
```

**Review by jplatte — APPROVED** [review]

**Review by seanmonstar — APPROVED** [review]

**Pull request merged**
