### PR TITLE
Update base64 and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by seanmonstar** [comment]
Mind leaving the version bump out, as that's done as part of the publish process.

**Comment by Eijebong** [comment]
Sure, sorry I'm used to force bumps everywhere :p

**Comment by seanmonstar** [comment]
Thanks :D

**Comment by nox** [comment]
No WPT issue complained in Servo, the plot deepens. Never the less, is it specified that `Basic $thetoken` must be separated by a single space? I'm wondering about (this line)[https://github.com/hyperium/headers/blob/0fca77932ac141ca3b46839ef949b621409382cc/src/common/authorization.rs#L145].

**Comment by seanmonstar** [comment]
Hm, nope, [looks like it's `scheme 1*SP token68`](https://tools.ietf.org/html/rfc7235#section-2.1). 🤷‍♂️

**Pull request merged**
